spring:
  datasource:
    url: jdbc:h2:file:/data/drones-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  profiles:
    active: "enable_flyway_profile"
    flyway:
      enable: true

